version: "3.4"
services:
  share:
    # image: quay.io/alfresco/alfresco-share:7.1.1.10
    build: ./build/share
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: acs
      REPO_PORT: 8080
    ports:
      - "8180:8080"
      - "9898:8888"
    # volumes:
    #   - ./ext/audit-log-browser-share-2.0.0.jar:/usr/local/tomcat/webapps/share/WEB-INF/lib/audit-log-browser-share-2.0.0.jar
  acs:
    # image: quay.io/alfresco/alfresco-content-repository:7.1.1.10
    build: ./build/platform
    environment:
      JAVA_TOOL_OPTIONS: "-Dencryption.keystore.type=JCEKS -Dencryption.cipherAlgorithm=AES/CBC/PKCS5Padding -Dencryption.keyAlgorithm=AES -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore -Dmetadata-keystore.password=mp6yc0UD9e -Dmetadata-keystore.aliases=metadata -Dmetadata-keystore.metadata.password=oKIWzVdEdA -Dmetadata-keystore.metadata.algorithm=AES"
      # JAVA_OPTS: '
      #   -Dsolr.secureComms=secret
      #   -Dsolr.sharedSecret=secret
      #   -Dfile.encoding=UTF-8
      #   -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
      #   '
      JAVA_OPTS: '
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.driver=org.postgresql.Driver
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dalfresco_user_store.adminpassword=209c6174da490caeb422f3fa5a7ae634
        -Dsystem.preferred.password.encoding=bcrypt10
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.port.ssl=8983
        -Dsolr.secureComms=secret
        -Dsolr.baseUrl=/solr
        -Dindex.subsystem.name=solr6
        -Dsolr.sharedSecret=secret
        -Dalfresco.host=${SERVER_NAME}
        -Dalfresco.port=443
        -Dapi-explorer.url=https://${SERVER_NAME}:443/api-explorer
        -Dalfresco.protocol=https
        -Dshare.host=${SERVER_NAME}
        -Dshare.port=443
        -Dshare.protocol=https
        -Daos.baseUrlOverwrite=https://${SERVER_NAME}/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Ddeployment.method=DOCKER_COMPOSE
        -Dcsrf.filter.enabled=false
        -Dopencmis.server.override=true
        -Dopencmis.server.value=https://${SERVER_NAME}:443
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Dcsrf.filter.enabled=false
        -Dalfresco.restApi.basicAuthScheme=true
        -XX:+UseG1GC -XX:+UseStringDeduplication
        -Dgoogledocs.enabled=true
        -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
        -Dmail.host=fakesmtp
        -Dmail.port=25
        -Dmail.username=alfresco
        -Dmail.from.enabled=true
        -Dmail.from.default=alfresco@no.reply
        -Dmail.password=dummy
        -Dmail.protocol=smtp
        -Dmail.encoding=UTF-8
        -Dmail.smtp.auth=true
        -Dmail.smtp.starttls.enable=true
        -Dmail.testmessage.send=true
        -Dmail.testmessage.to=dummy@example.com
        -Dmail.testmessage.subject="TEST SERVER"
        -Dmail.testmessage.text="SERVER STARTED UP"
        -Daudit.enabled=true
        -Daudit.rm.enabled=true
        -Daudit.alfresco-access.sub-actions.enabled=true
        -Daudit.alfresco-access.enabled=true
        -Daudit.filter.alfresco-access.default.enabled=true
        -Daudit.filter.alfresco-access.transaction.type="cm:folder;cm:content;st:site;~cm:person"
        -Daudit.filter.alfresco-access.default.user="~System;~null;.*"
        -Daudit.filter.alfresco-access.transaction.user="~System;~null;.*"
        -Dfile.encoding=UTF-8
        '
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - acs-volume:/usr/local/tomcat/alf_data
      # - ./audit:/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/extension/audit
      # - ./ext/audit-log-browser-platform-2.0.0.jar:/usr/local/tomcat/webapps/alfresco/WEB-INF/lib/audit-log-browser-platform-2.0.0.jar
    depends_on:
      - postgres
      - fakesmtp
  postgres:
    image: postgres:14.8
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5555:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
  solr6:
    image: alfresco/alfresco-search-services:2.0.3
    environment:
      SOLR_ALFRESCO_HOST: acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms.secret=secret"
    ports:
      - "8983:8983"
    volumes:
      - ass-volume:/opt/alfresco-search-services/contentstore
      - ass-volume:/opt/alfresco-search-services/data
  activemq:
    image: alfresco/alfresco-activemq:5.16.1
    mem_limit: 1g
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP
  fakesmtp:
    image: hatamiarash7/fake-smtp:latest
    ports:
      - 1025:25
    volumes:
      - /tmp/fakemail:/output
volumes:
  acs-volume:
    external: true
  db-volume:
    external: true
  ass-volume:
    external: true
